version: '3.4'

services:
    mongo:
        image: marketplace_mongo
        build:
            context: ./mongoDb
            dockerfile: Dockerfile
        volumes:
            - "./mongoDb/mongoVolume/db:/data/db"
        restart: always
        ports:
            - "27019:27017"
        command: [--auth]   
        environment: 
            MONGO_INITDB_ROOT_USERNAME: marketplace_admin
            MONGO_INITDB_ROOT_PASSWORD: marketplace_pwd
    authentication_service:
        image: authentication_service
        build:
            context: ./authentication_service
            dockerfile: Dockerfile
        ports:
            - "7001:7001"
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://marketplace_admin:marketplace_pwd@mongo/authentication-service
            - SECRET_KEY=my-secretkey-to-change-in-prod
        restart: always
