version: '3.4'

services:
    dot_marketplace_file_server:
        image: dot_marketplace_file_server
        build:
            context: ./dot_marketplace_file_server
            dockerfile: Dockerfile
        ports:
            - "8001:8001"
        restart: always