version: "3.4"

services:
    dot_marketplace_node:
        image: dot_marketplace_node
        build:
            context: ./tasking_backend
            dockerfile: Dockerfile
        ports:
            - "9944:9944"
        environment:
            - CARGO_HOME=/builds/tasking_backend/.cargo
        volumes:
            - .:/builds/tasking_backend